hello-nrfcloud/firmware

- Dockerfile
- Dockerfile.twister
Use multi-line statements and SHELL
> ci(cd): improve Dockefile syntax

- .github/workflows/sonarcloud.yml
Add coverage to the SonarCloud workflow
> workflows: sonarcloud: Add coverage to the SonarCloud workflow

- app/src/modules/environmental/environmental.c
> fix: report atmospheric pressure in hPA

- .github/workflows/night.yml
- tests/night/Dockerfile
- tests/night/README.md
- tests/night/run-tests.sh
Test on target, on self-hosted runner
> add nightly workflow

- .github/workflows/sonarcloud.yml
This commit adds coverage exclusions to the SonarCloud workflow.
> workflows: sonarcloud: add coverage exclusions

- tests/on_target/Dockerfile
- tests/on_target/run-tests.sh
- tests/on_target/tests/test.py
- tests/on_target/utils/flash_tools.py
> tests: on_target: fix device flashing

- .github/workflows/on_target.yml
Remove trigger on pull request.
> tests: on_target: remove trigger on pr

- app/src/modules/environmental/environmental.c
- app/src/modules/transport/Kconfig.transport
- app/src/modules/transport/transport.c
> app: transport: Use task watchdog service

- app/src/modules/trigger/Kconfig.trigger
- app/src/modules/trigger/trigger.c
Update to use task watchdog service.
> app: trigger: Use task watchdog service

- app/src/modules/trigger/trigger.c
Fix log message for initialization of dk_buttons_init().
> modules: trigger: Fix log message

- app/src/common/message_channel.h
- app/src/modules/app/app.c
- app/src/modules/app/app_object.cddl
- app/src/modules/led/led.c
- app/src/modules/trigger/trigger.c
Some CBOR fields are optional. Update the CDDL schema and code to not fail when missing.
> modules: Fix optional CDDL fields

- app/src/modules/trigger/Kconfig.trigger
Change default update interval to 3600 seconds.
> modules: trigger: Change default update interval

- .github/workflows/dfu_check.yml
- README.md
- app/Kconfig.sysbuild
- app/sample.yaml
- west.yml
Update the app config to be able to build for Thingy:91 X using sysbuild.
> app: Add sysbuild config

- .github/workflows/on_target.yml
New merged.hex path since sysbuild, need fix.
> workflow: on_target: fix build

- .github/workflows/attach_release_assets.yml
> ci: add permissions

- app/src/modules/trigger/trigger.c
Refresh timers upon config update.
> modules: trigger: Refresh timers upon config update

- app/src/modules/trigger/trigger.c
> modules: trigger: Cleanup timing handling

- .github/workflows/attach_release_assets.yml
> workflow: attach_release_assets: set dut1 segger

- tests/module/environmental/src/main.c
Print the C definition needed to fix the red test if we do a conscious decision to accept the new value.
> app: module: environmental: Add better error handling

- README.md
> README: Update with nightly badge

- app/src/modules/battery/bat_object.cddl
- app/src/modules/environmental/env_object.cddl
- tests/module/environmental/src/main.c
This commit adds a range to the basetime object.
> app: add range to basetime

- app/src/modules/fota/fota.c
- app/src/modules/transport/transport.c
- drivers/sensor/gas_sensor_dummy/gas_sensor.c
- lib/simple_config/simple_config.c
- tests/lib/simple_config/src/main.c
tests: simple_config: Reset fakes during setup
treewide: Fix maintainability issues reported by sonarcloud
> Fix sonarcloud issues in main

- README.md
Add sonarcloud badge that shows quality gate status.
> README: Add sonarcloud badge

- app/src/modules/battery/battery.c
Addressing issues found by SonarCloud with regards to code complexity.
The module thread complexity is reduced by splitting out initialization and message handling to separate functions.
> app: modules: battery: Improve code quality

- .github/workflows/docker_publish.yml
- tests/on_target/Dockerfile
Move docker image from personal to repo account.
> workflows: add a docker publish workflow

- app/CMakeLists.txt
- app/Kconfig
- app/overlay-memfault.conf
- app/sample.yaml
- app/src/common/message_channel.h
- app/src/modules/app/app.c
- app/src/modules/battery/battery.c
- app/src/modules/environmental/environmental.c
- app/src/modules/location/location.c
- app/src/modules/memfault/CMakeLists.txt
- app/src/modules/memfault/Kconfig.memfault
- app/src/modules/memfault/memfault.c
- app/src/modules/transport/transport.c
> wip: modules: network: Add support for Memfault

- .github/workflows/build.yml
Build with Memfault by default
> ci: Build with Memfault by default

- app/src/modules/app/app.c
- app/src/modules/app/app_object.cddl
Make LwM2M object optional, new devices will not have the LwM2M object present in their shadow.
> modules: app: Make LwM2M object optional

- app/src/modules/transport/transport.c
Remove call to device_status_update(). The function is not needed as the nRF Cloud CoAP library will automatically update the device shadow when connecting to the cloud.
> modules: transport: Remove call to device_status_update()

- west.yml
Pull in fix for reporting of sdkversion
> west: Pull in fix for reporting of sdkversion

- README.md
Update with status badge for target tests
[skip ci]
> README: Update with status badge for target tests

- .github/workflows/on_target.yml
Use the docker image pushed to package
registry.
> workflows: on_target: use package test docker

- tests/on_target/tests/conftest.py
- tests/on_target/tests/test_uart_output.py
> tests: on_target: button press test

- .github/workflows/build.yml
Configure app firmware version for Memfault, so the correct version is reported.
Fixes #209
> workflows: build: Configure version for Memfault

- app/src/modules/battery/CMakeLists.txt
- app/src/modules/environmental/CMakeLists.txt
- tests/module/environmental/CMakeLists.txt
Fix copy-paste error in CMakelists.
> modules: Fix copy-paste error in CMakeLists.txt

- tests/on_target/tests/test_uart_output.py
Fix payload regex in uart test.
> test: on_target: fix payload regex

- app/src/modules/led/led_pwm.c
- app/src/modules/shell/shell.c
- app/src/modules/trigger/Kconfig.trigger
- app/src/modules/trigger/trigger.c
Disable Uart and led PWM for low power.
Also made a Kconfig for Poll Mode duration
> modules: low power

- app/boards/thingy91x_nrf9151_ns.overlay
- app/src/modules/shell/shell.c
uart1 needs to be powered down when
in normal mode.
> modules: shell: shut uart1 off in normal mode

- .gitignore
Ignore an auto-generated file on macOS.
> treewide: Add .DS_Store to .gitignore

- app/src/modules/trigger/trigger.c
Fix issue where the GNSS event would trigger sampling immediately after the GNSS was disabled.
With the new changes we trigger sampling afer the update interval when the GNSS disabled event is received.
> modules: trigger: Don't trigger sampling on GNSS disabled

- tests/on_target/tests/test_uart_output.py
Update expected log to make the on target test pass. The log statement was changed in commit 0d42ab8f.
> tests: on_target: Update expected log

- west.yml
> west.yml: Update sdk-nrf hash

- .gitignore
This reverts commit 6443b45a5fbc1a46a5f3eceb44de7e82a8a5183b.
> treewide: Remove .DS_Store from .gitignore

- tests/on_target/tests/test_uart_output.py
Update expected string to match the new output from UART.
> tests: on_target: Update expected string

- app/src/modules/led/led.c
Update color if LED is already set by reentering
STATE_LED_SET triggering the entry function.
> modules: led: Update color if LED is already set

- tests/on_target/README.md
The Readme now points to the official docker image.
> tests: on_target: Update README.md

- west.yml
> manifest: Update sdk-nrf

- tests/on_target/tests/test_uart_output.py
Expect shadow and fota poll triggers on button press. Remove some expected output as the order is not guaranteed.
> tests: on_target: Cleanup expected order

- tests/on_target/README.md
- tests/on_target/tests/conftest.py
- tests/on_target/tests/test_fota.py
> tests: on_target: fix test on target

- tests/module/trigger/src/main.c
Fix test to accommadate for 30 second poll interval
> tests: modules: trigger: Fix test

- tests/on_target/tests/conftest.py
- tests/on_target/tests/test_fota.py
> tests: on_target: add mfw delta fota test

- app/CMakeLists.txt
> app: Fix the project name in CMakeLists.txt

- tests/on_target/tests/test_fota.py
Adding app fota resumption test.
> tests: on_target: add fota resumption test

- .github/workflows/on_target.yml
Adds a short test result summary to the actions page.
> github: Add test results

- tests/on_target/tests/test_fota.py
fix string check in fota test.
> tests: on_target: fix fota test

- README.md
New workflow needs update in badge.
> README: update nightly workflow badge

- .github/workflows/on_target.yml
- .github/workflows/test.yml
- tests/on_target/tests/pytest.ini
- tests/on_target/tests/test_fota.py
Adding full modem fw fota update test.
> tests: on_target: add full mfw fota test

- .github/workflows/test.yml
On push workflow is broken. This fixes it.
> tests: on_target: fix on push test

- west.yml
Updated west.yml to point to a PR with tempfix for cloud bug
> manifest: point to cloud tempfix pr

- tests/on_target/tests/test_fota.py
Button press is no longer neededd to trigger fota.
> tests: on_target: buttonless fota

- tests/on_target/Dockerfile
Use slim debian python image.
Replace deprecated developer.nordicsemi.com link.
Replace deprecated golang link.
> target_tests: Docker update

- .github/workflows/on_target.yml
> test: Use new docker image

- tests/on_target/README.md
Update Readme file with new docker image.
> tests: on_target: update README

- app/src/modules/shell/shell.c
Add option to disable UART pm for better debugging.
> modules: shell: uart pm runtime configurable

- app/src/modules/shell/Kconfig.shell
- app/src/modules/shell/shell.c
Add a kconfig for uart power management.
> modules: shell: kconfig for uart pm

- tests/on_target/tests/test_fota.py
- tests/on_target/utils/hellonrfcloud_fota.py
> tests: on_target: fix fota

- tests/on_target/tests/test_fota.py
Skip fota when posting a job fails.
> tests: on_target: skip fota

- .github/workflows/build.yml
This should fix on_target tests.
> ci: fix typos in connectivity_bridge image

- tests/on_target/tests/conftest.py
- tests/on_target/tests/test_fota.py
- tests/on_target/utils/hellonrfcloud_fota.py
- tests/on_target/utils/uart.py
Cancel pending fota jobs at teardown.
Also scan for assert in logs.
> tests: on_target:  cancel pending fota and scan for assert

- app/src/modules/location/location.c
> modules: location: Request all location sources

- app/src/modules/location/location.c
Add mode change to after default is set.
The set default function forces the mode to fallback mode.
> location: Add mode change to after default is set

- .github/workflows/publish-symbol-files-to-memfault.yml
> ci: fix memfault upload workflow

- app/src/modules/led/led_pwm.c
Fix LED PWM ready check when setting RGB values.
> modules: led: Fix LED PWM ready check

- tests/on_target/tests/test_fota.py
- tests/on_target/utils/hellonrfcloud_fota.py
Increase tiimeout for fota success reported to cloud.
> tests: on_target: increase fota test timeout

- tests/on_target/tests/test_fota.py
Remove cloud check on fota test.
> tests: on_target: no cloud check on fota

- .github/workflows/on_target.yml
- tests/on_target/Dockerfile
Apply config patch for nrfutil device 1Mbaud.
> workflow: on_target: patch nrfutil 1Mbaud

- tests/on_target/utils/thingy91x_dfu.py
Fix nrf91 bootloader update by specifying the new baudrate.
> ci: specify baudrate for mcumgr dfu

- .github/workflows/on_target.yml
Fix ci by quarantine dfu test and fix artifacts
> tests: on_target: fix ci

- tests/on_target/Dockerfile
- tests/on_target/README.md
Update jlink for latest nrfutil device.
> tests: on_target: jlink v794i

- tests/on_target/utils/hellonrfcloud_fota.py
Increase rest calls timeout of fota api.
> tests: on_target: increase fota api timeout

- .github/workflows/build.yml
- .github/workflows/lib/nameRegEx.mjs
- .github/workflows/lib/nameRegEx.test.mjs
- .github/workflows/publish-firmware-bundles-tests.yml
- .github/workflows/register-firmware-bundles.mjs
To allow FOTA update to the debug version.
> workflow: Create and upload debug bundle to nRF Cloud

- .github/workflows/on_target.yml
- tests/on_target/README.md
- tests/on_target/tests/test_serial_dfu.py
- tests/on_target/utils/flash_tools.py
- tests/on_target/utils/thingy91x_dfu.py
Fix and refactor dfu test and utils.
> tests: on_target: refactor dfu test

- tests/on_target/Dockerfile
Clean some leftovers in dockerfile.
> tests: on_target: cleanup dockerfile

- .github/workflows/build.yml
Add west blob command to fetch hal_nordic.
> workflows: build: add west blobs hal_nordic

- tests/on_target/tests/test_serial_dfu.py
Dfu test is unstable, working on a fix.
> tests: on_target: quarantine bl dfu test

- tests/on_target/utils/test_uart.py
- tests/on_target/utils/uart.py
wait_for_str no longer requires order.
Added wait_for_str_ordered().
> test: uart: Rework wait_for_str()

- tests/on_target/README.md
- tests/on_target/tests/test_serial_dfu.py
- tests/on_target/utils/flash_tools.py
- tests/on_target/utils/logger.py
- tests/on_target/utils/thingy91x_dfu.py
Fix for dfu test, both nrf91 and nrf53 dfu.
> tests: on_target: fix dfu test

- .github/workflows/on_target.yml
Fix to store log artifacts even when fails occur.
> tests: on_target: store log artifacts always

- tests/on_target/tests/conftest.py
Fix bug in get_uarts(), where uarts are duplicated.
> tests: on_target: fix bug in get_uarts()

- .github/workflows/on_target.yml
nrfutil patch is no longer needed, remove it.
> tests: on_target: remove outdated nrfutil patch

- .github/workflows/on_target.yml
- app/src/modules/location/location.c
- tests/on_target/tests/pytest.ini
- tests/on_target/tests/test_location.py
adds location tests for Wi-Fi and GNSS.
GNSS not active yet.
> test: on_target: add location tests

- tests/on_target/tests/test_serial_dfu.py
- tests/on_target/utils/flash_tools.py
- tests/on_target/utils/thingy91x_dfu.py
Add uart and version checks on dfu test.
> tests: on_target: dfu checks

- tests/on_target/README.md
Updates on on target tests readme.
> tests: on_target: update tests readme

- app/CMakeLists.txt
> CMakeLists: Fix if statement

- west.yml
> treewide: Update manifest

- app/prj.conf
> prj.conf: Remove duplicate configs

- app/prj.conf
> prj.conf: Increase AT monitor heap size

- .github/workflows/attach_release_assets.yml
- .github/workflows/build.yml
- .github/workflows/dfu_check.yml
- .github/workflows/on_target.yml
- .github/workflows/test.yml
- scripts/pmr_nrf91.txt
Refactor workflows using build. This is to reduce workflow times.
> ci: reuse build step more

- .github/workflows/on_target.yml
- .github/workflows/test.yml
test needs a very specific name apparently
> ci: rename target test

- .github/workflows/attach_release_assets.yml
The attempt on reusing the previous build didn't work.
> ci: revert attach release assets change

- app/src/modules/led/led_pwm.c
Increase LED PWM strength by decreasing period to MAX period value.
> led: Increase LED PWM strength by decreasing period

- README.md
Update folder naming to use hello nrf cloud instead of oob
> README: Update folder naming

- west.yml
> manifest: Update to v2.8.0-rc2

- tests/on_target/utils/test_uart.py
- tests/on_target/utils/uart.py
This implementation had issues.
> tests: Fix uart_ordered() check

- tests/on_target/tests/test_fota.py
- tests/on_target/tests/test_location.py
- tests/on_target/tests/test_uart_output.py
- tests/on_target/utils/uart.py
Check that we get OK from the modem after running at commands. Add retry logic.
> tests: xfactoryreset: Add retry, check return value

- ARCHITECTURE.md
This patch adds some documentation about the general structure of the app in ARCHITECTURE.md.
> docs: add architecture documentation

- tests/on_target/Dockerfile
git is not installed currently. Fix for that.
> tests: on_target: add git to dockerfile

- .github/workflows/on_target.yml
- tests/on_target/README.md
git and new requirements have been installed.
> tests: on_target: new test docker image

- .github/workflows/test.yml
Test workflow needs write permissions.
> workflows: write permission to test stage

- .github/workflows/on_target.yml
- tests/on_target/tests/test_conn_bridge.py
- tests/on_target/tests/test_serial_dfu.py
- tests/on_target/utils/flash_tools.py
- tests/on_target/utils/uart.py
Move hex files definitions out of workflow files.
Remove duplicate constants definitions also.
> ci: refactor hex handling

- tests/on_target/tests/test_power.py
Increase PSM time displayed in html power plot.
> tests: on_target: more PSM measurements

- .github/workflows/on_target.yml
- .github/workflows/test.yml
- tests/on_target/requirements.txt
- tests/on_target/tests/conftest.py
- tests/on_target/tests/pytest.ini
- tests/on_target/tests/test_bridge/test_conn_bridge.py
- tests/on_target/tests/test_bridge/test_serial_dfu.py
- tests/on_target/tests/test_functional/test_fota.py
- tests/on_target/tests/test_functional/test_location.py
- tests/on_target/tests/test_functional/test_traces.py
- tests/on_target/tests/test_functional/test_uart_output.py
- tests/on_target/tests/test_ppk/test_power.py
- tests/on_target/utils/test_uart.py
Add html report
Restructure tests, markers
> tests: Add report, restructure

- .github/workflows/on_target.yml
- tests/on_target/tests/test_functional/test_fota.py
- tests/on_target/tests/test_functional/test_memfault.py
Set default value for pytest_path.
Fix wrong fixture.
Move memfault test.
> tests: Fix workflow

- .github/workflows/on_target.yml
- .github/workflows/test.yml
Markers on schedule need to evaluate to empty string.
> workflows: fix no markers on schedule

- .github/workflows/test.yml
> workflows: test on shcedule

- .github/workflows/test.yml
> workflows: test on schedule, second attempt

- tests/on_target/tests/test_functional/test_memfault.py
Catch exceptions when accessing reboot count.
> tests: memfault: Catch exception on testing memfault event

- .github/workflows/on_target.yml
> workflows: fix markers

- .github/workflows/test.yml
Reset nightly cron to midnight.
> workflows: reset nightly cron

- .github/workflows/on_target.yml
- .github/workflows/test.yml
> workflows: fix markers again

- docs/about.rst
Add minor doc update to test the build workflow.
> docs: Test build worfklow

- .github/workflows/docs-build-and-publish.yml
Use GITHUB_TOKEN for GitHub token variable.
> workflows: Update github token environment variable

- docs/about.rst
- docs/architecture.rst
- docs/gsg_guide.rst
- docs/index.rst
- docs/release_notes.rst
- docs/troubleshooting.rst
doc fixes to the Hello nRF cloud docs
as per the review comments recieved.
> doc: doc fixes to the Hello nRF cloud docs

- tests/on_target/tests/test_functional/test_fota.py
> tests: on_target: small fix test fota

- .github/workflows/docs-build-and-publish.yml
Empty commit is failing currently, this should fix it.
> docs: commit if changes only

- docs/known_issues.rst
Fix typo in Kconfig option reference.
> docs: Fix typo

- tests/on_target/tests/conftest.py
- tests/on_target/tests/test_functional/test_fota.py
Fota resumption test was commented out.
Re-introduce it.
> tests: on_target: re-add fota resumption

- tests/on_target/tests/test_functional/test_fota.py
Update tests to use mfw 2.0.2.
> tests: on_target: use 202 mfw

- tests/on_target/tests/test_bridge/test_conn_bridge.py
- tests/on_target/tests/test_functional/test_fota.py
> tests: on_target: some code cleanup

- docs/links.txt
- docs/troubleshooting.rst
Add instructions to recover broken thingy91x devices.
> docs: factory reset

- docs/links.txt
> doc: Add link for devzone

- .github/workflows/docs-build-and-publish-zooomin.yml
> workflows: small fix zoomin

- .github/workflows/on-push-zoomin-publish.yml
- docs/tags.yml
updates to doc publish workflow
and the tag files
> doc: updates to doc publish workflow

- .github/workflows/on-push-zoomin-publish.yml
Updated the "on-push-zoomin-publish.yml" file to
upload docs to Zoomin prod.
> doc: Updates to upload doc to Zoomin prod

- .github/workflows/docs-build-and-publish-zooomin.yml
Update correct path for Zoomin prod
upload.
> doc: Update correct path for Zoomin prod

- docs/links.txt
- docs/troubleshooting.rst
Link to new recovery guide in Tech Docs.
> doc: link to new recovery guide

- README.md
- docs/antennatuning.rst
- docs/index.rst
- docs/links.txt
Add the Antenna Tuning on Thingy:91 X
TECHDOC-4033
> doc: Add the Antenna Tuning on Thingy:91 X

- docs/antennatuning.rst
- docs/links.txt
Update link of the Ignion's antenna tuning page
> doc: Update link of the Ignion's antenna tuning page
