.github/workflows/build.yml
Dockerfile

nrfutil toolchain-manager installs in `~/.nrfutil`, however when preparing a Docker image for GitHub Actions, they will launch into the Container, setting `$HOME` to `/home/github` and mounting the local filesystem over `/home/github`, so the `.nrfutil` folder is no longer visible. 
This sets `NRFUTIL_HOME` to a location that is outside of the mounted home directory.

ci: set NRFUTIL_HOME to shared location

---

README.md

Erase is needed because the use of UICR.

docs: Add --erase to west flash command

---

app/sample.yaml

Due to a bug in zephyr, compiler complains about an variable that may be used unitialized. This is fixed in zephyr commit
a6583f253eca3379f81b22481dcb30848e6d5665.
This patch temporarily disables the warning to get the build pass.

app: Temporarily ignore maybe-unitialized compile error

---

app/src/modules/battery/battery.c

Only include state of charge and charging state, initially we don't care about the rest.
For now, we are also removing the burst functionality. Running nrf_fuel_gauge_process() once per TRIGGER should hopefully be accurate enough.

src: modules: battery: Cleanup

---

zephyr/module.yml

Remove board_root and dts_root from zephyr module. These are meant for large projects that defines new boards. This project only uses an existing board defined in sdk-nrf.
This fixes a build warning.

zephyr: module.yml: remove unnecessary settings

---

app/src/modules/battery/bat_object.cddl
app/src/modules/battery/battery.c
app/src/modules/environmental/env_object.cddl
app/src/modules/environmental/environmental.c

This patch moves the timestamp of the
battery and environmental modules to base time.
This is for SenML compliance.

app: move timestamp to base time

---

.github/workflows/sonarcloud.yml

It seems that that if the build wrapper gets confused when the unit tests are run after it was was invoked with the build command. This leads to an java IO Exception during sonarcloud run. This patch aims to fix that by moving the unit test stage ahead of the build wrapper run.

workflow: sonarcloud: Make unit tests run first

---

.github/workflows/sonarcloud.yml

twister was silently skipping coverage generation if the
coverage-platform parameter was not provided. This lead to no coverage
files being generated when invoking with the --integration option. This
is now fixed.
As a side, we do not need to separate the build and the test steps.
Signed-off-by: Balaji Srinivasan <balaji.srinivasan@nordicsemi.no>

workflow: sonarcloud: fix coverage generation

---

.github/workflows/sonarcloud.yml
tests/lib/simple_config/testcase.yaml

This patch makes the test executable by twister on native_sim instead of native_posix. This is done to align with the other unit test in the repo and also it is a more modern platform for unit tests.

tests: simple_config: Move to native_sim

---

app/src/modules/location/Kconfig.location
app/src/modules/location/location.c

Updated the location module to use zbus subscribe instead of a listener for consistency and easier logic. Removed semaphores and modem lib connection handling. Connection handling might be needed unless the location lib doesn't handle this internally, but it should probably be dealt with using the Zephyr State Machine Framework.

app: location: Use zbus subscriber instead of listener

---

app/src/modules/app/app.c

Don't throw assertion on decoding failure.
This is to safeguard against potential protocol changes that may break decoding. If this happens a firmware update is likely needed to resolve the issue.

modules: app: Don't throw assertion on decoding failure

---

app/src/modules/app/app_object.cddl

Extended the schema by adding 'any' type members so that the schema is future proof and the app can respond to any new additional fields that may be populated by the cloud side

app: Make app_object schema future proof

---

.github/workflows/on_target.yml

The CONFIG_NRF_CLOUD_CLIENT_ID_PREFIX and DCONFIG_NRF_CLOUD_SEC_TAG are now by default set in the app's prj.conf. Hence this is not necessary when invoking twister.

workflow: on_target: Remove extra build parameters

---

app/sample.yaml

This reverts commit faf3262b7642334ded3a66b72f49c1b293fcccd0.
The warning is now fixed in the zephyr version included by latest ncs.

Revert: "app: Temporarily ignore maybe-unitialized compile error"

---

.github/workflows/attach_release_assets.yml
.github/workflows/build.yml
.github/workflows/dfu_check.yml
.github/workflows/on_target.yml

When a release is created this new workflow calls the other build
and test workflows and uploads the tested artifacts into github
release.
The existing workflows were modified to make them callable from other
workflows.
Build workflow now uploads the artifacts so that they can be added to
the release. The build workflow uploads the hex, bin and the .config
file. The names of the files will have the sha if built from main and
the tag name if built from a tag.
The release will look like this with the assets (tested on private fork)
The workflow run will look similar to this.
Fixes: https://github.com/hello-nrfcloud/firmware/issues/139

workflow: Add make release workflow

---

.github/workflows/sonarcloud.yml

Sonarcloud will now be triggered only for changes in .c and .h files.

worfklow: sonarcloud: Make it trigger only for c and h files changes

---

.github/workflows/on_target.yml

In order to provide options for input, the type: choice must be specified. This is now fixed.

workflow: on_target: Fix missing type in inputs

---

.github/workflows/on_target.yml
tests/on_target/run-tests.sh
tests/on_target/tests/conftest.py
tests/on_target/tests/test_uart_output.py

Previously the on_target workflow was re-doing the steps done by the build workflow. But since now the build workflow uploads the built firmware as artifacts, we now have the possibility to re-use it. The on_target workflow now calls the build worfklow and downloads its artifaacts to perform the tests.
The test fraemwork code was modified to accept new input argument firmware-hex that points to the hex file to test.

workflow: on_target: Reuse build workflow to build firmware

---

.github/workflows/attach_release_assets.yml

Now that the on_target workflow triggers the build on its own, we do not need to trigger it from this workflow.

workflow: attach_release_assets: Remove extra dependency on build

---

.github/workflows/attach_release_assets.yml

A repo checkout was needed in order to make the gh command succeed. Also the version is now obtained from github event instead of depending on the environment variable. The environment variable was previously set by build workflow which is now triggered by the on_target workflow. The added link the chain makes the environment variable inaccesible to this workflow.

workflow: attach_release_assets: Fix publishing to nrfcloud

---

app/prj.conf

Removed CONFIG_DEBUG from application. This also removes
the need for having to set the enable size optimizations separately.

app: Remove debug configs and reduced heap size

---

app/src/modules/app/Kconfig.app
app/src/modules/app/app.c

Convert to MSG subscriber to ensure that the app module is able to receive messages from other modules with guaranteed delivery.
Fixes issue where the trigger module would send a POLL and DATA SAMPLE trigger at the same time, causing the app module to miss the POLL due to the payload being overwritten.

modules: app: Convert to MSG subscriber

---

tests/module/environmental/src/main.c

This function is not needed because we do not need to get call backs in the test for the trigger channel.

tests: environmental: Remove trigger_callback function

---

app/src/common/message_channel.c
app/src/common/message_channel.h
app/src/modules/app/app.c
app/src/modules/battery/battery.c
app/src/modules/environmental/environmental.c
app/src/modules/transport/transport.c
tests/module/environmental/src/main.c
tests/module/transport/src/transport_module_test.c

The battery and environment modules use date_time library to timestamp sampled data.
These modules will now wait until time is available before sampling and attempting to timestamp data.
The tas to send the TIME_AVAILABLE event is taken by the app module.

app: Add TIME_AVAILABLE event

---

.github/workflows/on_target.yml

Pass all secrets to build workflow so that the build workflow can access secrets like MEMFAULT_PROJECT_KEY when triggered from on_target workflow.

workflow: on_target: Pass secrets to build workflow

---

.github/workflows/on_target.yml

Make Target Tests run on every push to main. This is done to ensure that all commits on main are target tested so that when we make a release we know that we make it from a green commit.

workflow: on_target: Make the workflow run on push to main

---

.github/workflows/dfu_check.yml

Make the DFU image compatibility check run only for changes to certain files that may affect the image compatibility. On main, it will continue to run on all changes.

workflow: dfu_check: Make it run only on relevant changes

---

app/src/modules/battery/battery.c
app/src/modules/environmental/environmental.c

The zbus message was read both in the module task and in state run. Which caused errors and lead to an assertion error.
Removed the zbus msg read from the module task loop.

app: Fix double zbus msg read

---

app/src/modules/network/network.c

Enable modem events to get warning about modem reset loop.

modules: network: Enable modem events

---

app/src/modules/transport/transport.c

The log statement was printing the string with %p specifier. This is now fixed.

modules: transport: Fix print statement

---

app/src/modules/transport/transport.c

The print does not print useful information as it merely prints the readable bytes of the binary encoded payload. Printing the pointer instead may be slightly more useful for debugging purposes.
This reverts commit 4f9033734220784ab62e115f38930760684a9de7.

Revert "modules: transport: Fix print statement"

---

app/src/modules/network/conn_info.cddl
app/src/modules/network/network.c
tests/module/network/src/main.c

RSRP will now be reported along with energy estimate.
CDDL schema updated and made clearer to support this.
Tested by verifying the the RSRP in the Connection Info lwm2m object pane
Verified that there are no decoding errors in the lwm2m objects reported to cloud. 
Unit tests updated.
Fixes https://github.com/hello-nrfcloud/firmware/issues/105

Add RSRP reporting to cloud

---

app/src/modules/app/app.c
app/src/modules/battery/battery.c
app/src/modules/environmental/environmental.c
app/src/modules/location/location.c
app/src/modules/network/network.c
app/src/modules/shell/shell.c
app/src/modules/transport/transport.c

Use the same lowest application thread priority while creating all threads in the application.

treewide: Use same lowest application thread prio for all threads

---

.editorconfig

This patch copies the editorconfig file from Zephyr.

treewide: add editorconfig file

---

app/src/modules/trigger/trigger.c

Remove stopping of poll duration timer:
We need to keep this timer running to ensure that we go into the normal state where data sample and poll triggers are sent less frequently after 10 minutes.
Without this patch we will persist in the frequent poll state forever.

modules: trigger: Remove stopping of poll duration timer

---

scripts/connectivity_bridge.patch

This patch configures the bootloader to stay in recovery mode if no valid application is found. This is needed for an internal process.

ci: nrf53 bootloader: stay in recovery on fail

---

app/src/modules/fota/Kconfig.fota
app/src/modules/fota/fota.c

Limit polling for FOTA jobs to a minimum of 60 seconds. This is to reduce the power and data consumption of the device.
The values can be changed by setting the
CONFIG_APP_FOTA_POLL_INTERVAL_SECONDS option.

modules: fota: Limit polling for FOTA jobs

---

app/src/modules/app/app.c
app/src/modules/transport/transport.c
west.yml

Explicitly disconnect CoAP on network disconnect:
- Register listener that explicitly calls nrf_cloud_coap_disconnect() on lost LTE network.
This is needed due to the likelyhood of the transport module thread being blocked performing a CoAP request when the network disconnects.
- Send reconnection event on the transport private channel when calls to the nrf_cloud_coap_bytes send fails. This is to detect when the socket has been closed so that the transport module can reconnect.
- Update manifest to include updates to the nrf cloud coap library needed for this change.

modules: transport: Explicitly disconnect CoAP on network disconnect

---

app/config/memfault_trace_reason_user_config.def
app/src/common/message_channel.h
app/src/modules/app/app.c
app/src/modules/memfault/memfault.c

In case the cloud side returns an error it should be handled as a recoverable error. Do not attempt to parse the response, but report the error and return code to Memfault if Memfault is enabled.
After discussion with @simensrostad, we decided to call the Memfault macro directly from the code, so Memfault correctly sees what line sent the error. Also changed from generic errors to more specific errors for each use case.
CIA-1289

modules: app: Improve device shadow cloud errors

---

app/src/modules/led/led.c

Reenter STATE_RUNNING on network connected to ensure that the LED shows the correct pattern state when the network is reconnected.
Previously the yellow (searching for LTE netowork) was persisted.

modules: led: Reenter STATE_RUNNING on network connected

---

app/src/modules/network/Kconfig.network

Under certain conditions sampling connection quality can take upwards to 20 seconds (observed).
To prevent a WD kicking in the WDT is now increased to 30 seconds. (Added some extra seconds just in case)

modules: network: Increase WDT to 30 seconds

---

app/src/modules/transport/transport.c
app/src/modules/trigger/trigger.c
tests/module/trigger/src/main.c

Cancel ongoing connection work on LTE disconnect.
There is no point of trying to reconnect if LTE is disconnected.
_________________________________________________________________
When entering normal mode, schedule triggers after the respective
timeouts, not immediately.
This fix prevents the trigger module from firing triggers every time
the GNSS is disabled in normal mode.
This issue occurs when a trigger is sent, and GNSS finishes sampling,
causing an endless loop of back-and-forth triggers instead of
returning to the expected interval.

modules: Smaller fixes

---

west.yml

The PR 16808 has been merged, so the reference to sdk-nrf can be updated to the latest main sha.
Fixes #212

west: update sdk-nrf version

---

app/src/modules/trigger/trigger.c
tests/module/trigger/src/main.c

Add separate trigger for shadow polling. Polling now occurs every 20 seconds when the trigger module is actively polling cloud, and data sampling every 60 seconds. This is to preserve power and data usage. Previously both data sampling and shadow polling occured every 20 seconds.

modules: trigger: Add separate trigger for shadow poll

---

west.yml

Update sdk-nrf to pull in change that limits getting modem parameters to when the modem is not in offline mode.
The on target test currently fails quite often due to the modem being put in offline mode in between tests.
This in turn triggers a warning in the memfault lte integration layer that calls the modem info API that fail.

manifest: Update sdk-nrf

---

app/src/modules/location/location.c

Don't assert on location error. This event is notified when the underlying transport library fails to send location to nRF cloud, which is common during poor network conditions.
This is acceptable and the device should recover. Ideally we would have an event reserved for fatal errors.

modules: location: Don't assert on location error

---

.github/workflows/on_target.yml

The current latest docker version v2.0.0-preview32 has issues with  nrfutil device version. This patch pins the docker image version to  the last known working docker image to unblock CI.

workflow: on_target: Use fixed docker image version

---

tests/on_target/tests/test_uart_output.py

The latest changes in the firmware makes the firmware remain in blocked state until location is obtained (not just until GNSS was active). So we need to add a delay before simulating a button press and expect the frequent_poll_run trace.

tests: on_target: Add wait before button press

---

app/src/modules/network/network.c
tests/on_target/tests/test_uart_output.py
tests/on_target/utils/uart.py

Add test case for network loss
Since we are explicitly setting the mode in offline mode, also update calling of lte lc coneval API to not send fatal error if called with an unsupported functional mode.

on_target: Add test case for network loss

---

tests/on_target/Dockerfile

- Add apt-get clean after apt-get install to reduce size of the docker image.
- Avoid wget from following redirected links there by hardenining the security.
These problems where found by SonarLint.

Dockerfile: Clean apt-get cache and avoid wget redirects

---

app/src/modules/trigger/trigger.c

Poll for cloud changes and FOTA in blocked state.
Previously we only restarted the frequent poll duration timer. This change allows users to get the latest cloud config / FOTA job right away without waiting for the next poll interval.

modules: trigger: Poll on button press when blocked

---

app/src/modules/trigger/trigger.c

To circumvent a cloud issue currently being looked into we need to increase the frequent poll timer to 30 seconds to prevent the TLS session from being lost cloud side.

modules: trigger: Increase poll timer to 30 seconds

---

.github/workflows/on_target.yml
tests/on_target/README.md
tests/on_target/tests/pytest.ini
tests/on_target/tests/test_fota.py
tests/on_target/tests/test_uart_output.py

Splitting fota and uart tests in two steps in the workflow.

tests: on_target: split uart and fota steps

---

app/src/modules/network/conn_info.cddl
app/src/modules/network/network.c
tests/module/network/src/main.c

With the previous CDDL boundaries for RSRP, encoding would fail if the returned RSRP was not obtained (invalid).
Ignore invalid RSRP values:
- Make RSRP optional in CDDL schema
- Update tests

modules: network: Ignore invalid RSRP values

---

app/src/modules/battery/battery.c
app/src/modules/button/button.c
app/src/modules/environmental/environmental.c
app/src/modules/fota/fota.c
app/src/modules/network/network.c
app/src/modules/transport/transport.c
app/src/modules/trigger/trigger.c

Use 1 second as the default timeout when publishing on a zbus channel. Previously, different values were used, sometimes `K_NO_WAIT`. Using `K_NO_WAIT` is problematic if the channel is locked by another context when calling `zbus_chan_pub`. If this occurs, the API fails, which we currently handle by asserting. Increasing the timeout increases the chance of the API succeeding.

modules: Unify timeout for `zbus_chan_pub`

---

.github/workflows/attach_release_assets.yml
.github/workflows/build.yml

memfault sw type needs to be configured in MEMFAULT_NCS_FW_TYPE
Not only when pushing elf with --software-type arg

workflow: fix memfault sw type

---

app/prj.conf
app/src/modules/fota/fota.c
app/src/modules/led/Kconfig.led
app/src/modules/led/led_pwm.c
app/src/modules/transport/transport.c
tests/on_target/tests/test_fota.py

After modem FOTA the download client thread tries to put the modem into bootloader mode. However, this times out. Suspected reason is that the LED PWM handling is blocking the download client thread due to being scheduled in tight steps via the system workqueue (cooperative).
Also, reinstate eDRX setting in prj.conf that was removed by mistake.
AND, increase full modem test timeout to 30 minutes as it occasionally times out. (Slow download)

modules: Use dedicated workqueue for LED PWM handling

---

app/src/modules/app/Kconfig.app
app/src/modules/fota/Kconfig.fota
app/src/modules/fota/fota.c
app/src/modules/transport/Kconfig.transport
tests/on_target/tests/test_fota.py

Modem validation (shutdown and reinit in bootloader mode) fails quite often. Fix this by re-applying the modem image again after FOTA has finished.

modules: fota: Re-apply modem image after FOTA

---

app/overlay-modemtrace.conf
app/src/modules/memfault/Kconfig.memfault
app/src/modules/memfault/memfault.c

Add initial support for storing modem traces to flash, and upload to Memfault after a coredump. Currently there is not enough memory to initialize the flash map for the partition, but that can be implemented in a future improvement.

app: memfault: Initial support for modem trace handling

---

app/prj.conf

Revert main stack reduction to default 1024 and set it to 4096.

app: Revert main stack reduction

---

.github/workflows/build.yml
.github/workflows/on_target.yml
.github/workflows/publish-symbol-files-to-memfault.yml
.github/workflows/register-firmware-bundles.mjs
tests/on_target/README.md
tests/on_target/tests/conftest.py

Make the artifact names more obivous.
Also, for nRF5340 builds, separate HEX files for
APP core and NET core are released so nrfutil-device can be used.

ci: sanitize artifact names

---

.github/workflows/attach_release_assets.yml

The connectivity bridge assets have been missing since the renaming.

ci: fix connectivity-bridge release assets

---

app/src/modules/app/Kconfig.app

Increase watchdog timeout to avoid blocking during CoAP requests.

modules: app: Increase watchdog timeout

---

app/src/modules/transport/transport.c

Remove explicit disconnect on NETWORK_DISCONNECTED event. Since we are using connection ID we are technically connected on a logical level. Even though LTE is disconnected.
This is to prevent full new handshakes for every reconnect which increases data usage during spotty connections.

modules: transport: Remove explicit disconnect on NETWORK_DISCONNECTED

---

tests/on_target/tests/test_uart_output.py

Cloud connection is valid even though network connection is intermittently lost.

tests: on_target: no cloud check on network disconnect

---

.github/workflows/build.yml
app/src/modules/memfault/Kconfig.memfault
app/src/modules/memfault/memfault.c

Introduce option that controls whether data is uploaded on cloud
ready event or not. It's been observed that uploading data to
Memfault consumes a lot of data (and power) in poor network
conditions where cloud is toggling frequently between paused and
ready.

Memfault fixes

---

tests/on_target/tests/test_serial_dfu.py

this patch updates the expected bl version to 3 for nrf91.

ci: fix bl version in dfu test

---

.github/workflows/publish-symbol-files-to-memfault.yml

The debug version of the oob application was added to the attach release assets last week, but the symbol files (elf) was not uploaded to Memfault. This commit adds a step for uploading the elf for the debug build.

workflow: publish elf for debug version to memfault

---

.github/workflows/build.yml
.github/workflows/publish-symbol-files-to-memfault.yml

Add +debug to the version string when building the debug version and when uploading the debug elf to memfault.

workflow: Add +debug to the debug version

---

app/src/modules/app/Kconfig.app

Incrase payload buffer to 1024 bytes.
Its been observer that responses from nrf cloud gets truncated when requesting the full shadow post boot.
Increase the payload buffer to 1024 bytes to avoid truncation.

modules: app: Incrase payload buffer

---

app/src/modules/memfault/memfault.c

Add extra guard to enable UART modem traces.
This is to make the application build when using the modem trace snippet that forwards traces over UART.

modules: memfault: Add extra guard to enable UART modem traces

---

app/src/modules/app/Kconfig.app

The stack size was right on the limit for overflowing. Increasing to avoid that.

app: Increase app module stack size

---

.github/workflows/check-main-status-test.yml
.github/workflows/check-main-status.yml
.github/workflows/dfu_check.yml
.github/workflows/jest.config.js
.github/workflows/lib/checkMain.js
.github/workflows/lib/checkMain.test.js

The workflow checks the status of the main branch. When checks on main are failing the workflow should fail. Preventing adding more changes when main is broken.

workflow: Add check-main-status workflow

---

app/src/common/message_channel.h
app/src/modules/memfault/memfault.c

Clear modem traces after boot on no valid coredump. This is to prevent any issues related to non-volitile variables in the modem trace flash backend such as offset and size.
We have observed that some traces are corrupted and to potentially improve this we clear the modem traces after boot if there is no valid coredump.
Increase timeout when crashing to 10 seconds to allow more time for memfault to save the coredump and modem traces to be saved to flash.

memfault: Clear modem traces after boot on no valid coredump

---

.github/workflows/on_target.yml
tests/on_target/utils/logger.py

tests: on_target: test logs to artifacts

---

.github/workflows/sonarcloud.yml

The binary blob is needed to build Wi-Fi stack.

workflows: sonarcloud: Fecth Wi-Fi blob

---

README.md
tests/on_target/README.md

This add missing parts regarding getting started and on_target testing.
Signed-off-by: David Dilner <david.dilner@nordicsemi.no>

README: adding missing steps in documentation

---

app/src/modules/network/Kconfig.network

Increase watchdog timeout to 600 seconds to accommodate for CONEVAL that can take up to 10 minutes (conservatively) in NB-IoT when there is an ongoing cell search.
See NRF91-2230

modules: network: Increase watchdog timeout

---

.github/workflows/docker_publish.yml

Currently a new target-test docker image is built on every firmware release. Change this to build new docker image when a 'docker-vx.y.z' tag is pushed.

docker: Disconnect firmware releases and docker images

---

tests/on_target/tests/pytest.ini

adds missing markers for DFU and connectivity bridge

tests: on_target: add missing markers

---

app/CMakeLists.txt
app/overlay-modemtrace.conf

Set nRF Cloud CoAP security tag to a dev tag to
enable decoded DTLS traces. Dev tag for JWT generation is kept at 4242.

overlay-modemtrace.conf: Use dev security tag

---

.github/workflows/attach_release_assets.yml
.github/workflows/build.yml
.github/workflows/on_target.yml

This patch hopefully fixes the remaining references to the bootloader files.

ci: fix frozen bootloader references

---

.github/workflows/build.yml
.github/workflows/dfu_check.yml
tests/on_target/tests/test_serial_dfu.py
tests/on_target/utils/flash_tools.py
tests/on_target/utils/thingy91x_dfu.py

The bootloader version we want to use for production is actually 3, not 2. The test is updated to reflect this.
Also, the currently used slot is 1, so the update should go to slot 0.

ci: Bump nRF53 BL version to 3

---

.github/workflows/test.yml

CI build should use default "hello.nrfcloud.com-ci". Otherwise is we are not able to distinguish in memfault UI. And CI will just spam it.
Also, debug build is not needed for normal CI, only release.

workflows: revert memfault sw type and debug build

---

.github/workflows/dfu_check.yml

Remove unzip of debug build artifacts, failing.

workflows: dfu_check: no need for debug build

---

app/src/modules/led/led.h

Increase LED_MAX to UINT8_MAX to avoid error when
setting pulse width to UINT8_MAX when certain colors are set via WEB UI.

led: Increase LED_MAX to UINT8_MAX

---

app/src/modules/shell/shell.c

Add a short wait before UARTs are suspended to leave time to empty the buffers. Otherwise an assert will kick in because the TX_STOPPED event has not been received before suspending the UARTs.

modules: shell: Add wait before UARTs are suspended

---

.github/workflows/build.yml

There is no need to build when on_target files are modified.

workflows: dont build for on_target

---

.github/workflows/on_target.yml

If commit of ppk badge fails, do not mark the whole job as failed.

workflows: on_target: continue on error, commit badge

---

.github/workflows/build.yml

No need to build when only test workflows are affected.

workflows: skip building for test changes

---

.github/workflows/on_target.yml
tests/on_target/scripts/commit_badge.sh

Currently badge does not get committed if previous tests fail. Always commit it, script exits without fail if no file is found.

workflows: on_target: commit ppk badge always

---

.github/workflows/docs-build-and-publish.yml

Fix the copy step so that we don't end up with 'html/html/'.

workflows: Fix doc build copy step

---

.github/workflows/sonarcloud.yml
.github/workflows/test.yml
docs/index.rst
docs/links.txt
docs/requirements.txt

* Add introduction section to the documentation.
* Skip the Sonarcloud checks and build jobs when only docs have changed.

Docs: Add introduction

---

tests/on_target/tests/test_functional/test_location.py
tests/on_target/tests/test_functional/test_memfault.py

Relax timeouts to reduce CI instabilities.

tests: on_target: relax test timeouts

---

tests/on_target/tests/conftest.py

Currently t91x_board fixture is scoped module.
Uart therefore times out in test_fota.

tests: on_target: t91x_board fixture scoped function

---

tests/on_target/tests/test_functional/test_fota.py

Get latest bundle request is broken.
Use hard-coded bundleID as solution.

tests: on_target: fix app fota test

---

app/src/modules/led/led_pwm.c

Fix G and B color swap in the RGB PWM configuration. This can be removed when it is corrected in sdk-nrf.

app: boards: Fix LED color swap
